dist: focal
language: node_js
node_js:
  - 18.19.0
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - npm install -g codecov
after_success:
  - npm run report:coverage
  - codecov
