'use strict';

const HTTP_CLIENT_PORT = 80;
const HTTP_SERVER_PORT = 9999;
const HTTPS_CLIENT_PORT = 443;
const HTTPS_SERVER_PORT = 19999;

const BROWSER_TARGET = '#browser-content';

module.exports = {
  HTTP_CLIENT_PORT,
  HTTP_SERVER_PORT,
  HTTPS_CLIENT_PORT,
  HTTPS_SERVER_PORT,
  BROWSER_TARGET
};
