name: Test
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install pkg-config cairo pango libpng jpeg giflib librsvg

    - name: Install Node.js on ${{ matrix.os }}
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci
      env:
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig

    - name: Generate coverage report
      run: npm run report:coverage

    - name: Send coverage report
      uses: codecov/codecov-action@v3.1.1
      with:
        directory: ./reports/
